### ISSUE TITLE
Python2 support for RHEL/CentOS7

### ISSUE THREAD

**Issue by tuxmaster** [sdgroeve/ms2pip_c#15]
Hello,
are it possible to fix the app for python2, because the needed dependency's for python3 arr missing. 
It looks as the compute part will work, only the aggregation part will fail.

> starting workers...
> scanning peptide file... 3 spectra (~0.13 per cpu)
> merging results...
> Traceback (most recent call last):
>  File "/usr/bin/ms2pipC.py", line 758, in <module>
>    run(pep_file, spec_file=spec_file, vector_file=vector_file,
> params=params, num_cpu=num_cpu)
>  File "/usr/bin/ms2pipC.py", line 741, in run
>    all_preds = all_preds.append(r.get())
>  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
>    raise self._value

**Comment by anasilviacs** [comment]
Hi,

With python 2, if there is any error in the parallel part the traceback points to that line, but the actual error could be anywhere in `process_spectra` or `process_peptides` function. The code currently supports python 3 - we will definitely update the `README.md` to make this clear. We would recommend that you use python 3 to run this code, maybe using a virtual environment.
