### ISSUE TITLE
Peptides with a modification on the last amino acid return IndexError

### ISSUE THREAD

**Issue by RalfG** [sdgroeve/ms2pip_c#3]
When a peptide with a modification on the last amino acid is parsed, MS2PIPc returns an IndexError:
```merging results...
Traceback (most recent call last):
  File "ms2pipC.py", line 568, in <module>
     main()
  File "ms2pipC.py", line 135, in main
     all_spectra.extend(r.get())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
     raise self._value
IndexError: index 14 is out of bounds for axis 0 with size 14
```
In this case the peptide was `14|PhosphoS ATLLEDQQDPSPSS 2`.

**Comment by sdgroeve** [comment]
does pulling the latest version work?

**Comment by RalfG** [comment]
It's fixed!
